"""
report_agent.py — Report Agent
Uses Gemini to generate a full Markdown due-diligence report from all collected data.
"""

from .base_agent import BaseAgent
from ..llm import ask


class ReportAgent(BaseAgent):
    name = "report"
    description = "Uses Gemini to generate a full Markdown due-diligence report."

    def run(self, profile: dict | None = None, **kwargs) -> str:
        profile = profile or {}
        self.log_start({"company": profile.get("name")})

        name = profile.get("name", "Unknown Company")
        report = self._gemini_report(profile)

        self.log_done(f"Report generated for {name}")
        return report

    def _gemini_report(self, p: dict) -> str:
        name = p.get("name", "")
        founders = p.get("founders", [])
        founder_names = ", ".join(f.get("name", "") for f in founders) or "Unknown"
        github = p.get("github", {})
        news = p.get("news", {})
        market = p.get("market", {})
        score = p.get("score", 0)
        tier = p.get("tier", "Low")
        rationale = p.get("rationale", "")
        competitors = ", ".join(c.get("name", "") for c in market.get("competitors", [])[:3])

        prompt = f"""
Write a professional venture capital due-diligence report in Markdown for:

**Company**: {name}
**Industry**: {p.get('industry', '')} | **Stage**: {p.get('stage', '')} | **Location**: {p.get('location', '')}
**Product**: {p.get('product', p.get('description', ''))}
**Founders**: {founder_names}
**GitHub**: {github.get('total_stars', 0)} stars, {github.get('repo_count', 0)} repos
**News Sentiment**: {news.get('sentiment', 'neutral')} — {news.get('summary', '')}
**Market TAM**: {market.get('tam_estimate', 'N/A')} | Growth: {market.get('market_growth_rate', 'N/A')}
**Competitors**: {competitors}
**Investment Score**: {score}/100 ({tier})
**Rationale**: {rationale}

Structure the report with these sections (use ## headers):
1. Executive Summary
2. Company Overview
3. Team & Leadership
4. Technology & Product
5. Market Opportunity
6. Competitive Landscape
7. Recent Traction & News
8. Risk Factors
9. Investment Recommendation

Be specific, data-driven, and professional. Use bullet points where appropriate.
"""
        fallback = f"""# {name} — Due Diligence Report

## Executive Summary
**Score: {score}/100 ({tier})**
{rationale}

## Company Overview
{p.get('description', 'Information pending.')}

## Investment Recommendation
{'**Strong Buy** — High priority opportunity.' if tier == 'High' else '**Watch** — Monitor for further traction.' if tier == 'Medium' else '**Pass** — Does not meet current criteria.'}

---
*Generated by VenturePilot AI*
"""
        return ask(prompt, fallback=fallback)
